### ISSUE TITLE
How to save the sound?

### ISSUE THREAD

**Issue by Wu-XZ** [patmalcolm91/SumoSound#3]
I want to know how to save the sound that generated by the code to a .wav file? Look forward to your reply!

**Comment by patmalcolm91** [comment]
There is currently no built-in way in the SumoSound library to save the generated sound to a file. The reason for this is that the sound is generated in real time and sent to the PyOpenAL backend. Therefore, it would be quite difficult to guarantee a consistent simulation / playback speed that would sync up with any exported video animation of the simulation, for example.

For this reason, I would suggest that the best solution to getting a recording is to simultaneously record the sound and video of a running simulation using a screen recording program of your choice.

**Comment by Wu-XZ** [comment]
> There is currently no built-in way in the SumoSound library to save the generated sound to a file. The reason for this is that the sound is generated in real time and sent to the PyOpenAL backend. Therefore, it would be quite difficult to guarantee a consistent simulation / playback speed that would sync up with any exported video animation of the simulation, for example.
> 
> For this reason, I would suggest that the best solution to getting a recording is to simultaneously record the sound and video of a running simulation using a screen recording program of your choice.

Thank you very much! I have decided to use _pyaudio_ to directly record the sound from the computer. By doing this, the recording can be done automatically instead of manual operation.

**Comment by patmalcolm91** [comment]
Happy to help! If you want, feel free to post an example of how you used ``pyaudio`` to save the audio here in this thread, as it might be useful for future users.
